# Generated by Django 2.2 on 2019-05-07 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cartitem',
            table='t_cartitem',
        ),
    ]
