# Generated by Django 2.2 on 2019-05-10 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='t_order',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='t_orderitem',
        ),
    ]
